/*
 * This file is generated by jOOQ.
 */
package com.niq.datamodel;


import com.niq.datamodel.tables.Product;
import com.niq.datamodel.tables.ShopperShelf;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Niq extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>NIQ</code>
     */
    public static final Niq NIQ = new Niq();

    /**
     * The table <code>NIQ.PRODUCT</code>.
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>NIQ.SHOPPER_SHELF</code>.
     */
    public final ShopperShelf SHOPPER_SHELF = ShopperShelf.SHOPPER_SHELF;

    /**
     * No further instances allowed
     */
    private Niq() {
        super("NIQ", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Product.PRODUCT,
            ShopperShelf.SHOPPER_SHELF
        );
    }
}
