/*
 * This file is generated by jOOQ.
 */
package com.niq.datamodel;


import com.niq.datamodel.tables.Product;
import com.niq.datamodel.tables.ShopperShelf;


/**
 * Convenience access to all tables in NIQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>NIQ.PRODUCT</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>NIQ.SHOPPER_SHELF</code>.
     */
    public static final ShopperShelf SHOPPER_SHELF = ShopperShelf.SHOPPER_SHELF;
}
