/*
 * This file is generated by jOOQ.
 */
package com.niq.datamodel;


import com.niq.datamodel.tables.Product;
import com.niq.datamodel.tables.ShopperShelf;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in NIQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_PRODUCT_BRAND = Internal.createIndex(DSL.name("IDX_PRODUCT_BRAND"), Product.PRODUCT, new OrderField[] { Product.PRODUCT.BRAND }, false);
    public static final Index IDX_PRODUCT_CATEGORY = Internal.createIndex(DSL.name("IDX_PRODUCT_CATEGORY"), Product.PRODUCT, new OrderField[] { Product.PRODUCT.CATEGORY }, false);
    public static final Index IDX_SHOPPER_SHELF_PRODUCT = Internal.createIndex(DSL.name("IDX_SHOPPER_SHELF_PRODUCT"), ShopperShelf.SHOPPER_SHELF, new OrderField[] { ShopperShelf.SHOPPER_SHELF.PRODUCT_ID }, false);
}
