/*
 * This file is generated by jOOQ.
 */
package com.niq.datamodel;


import com.niq.datamodel.tables.Product;
import com.niq.datamodel.tables.ShopperShelf;
import com.niq.datamodel.tables.records.ProductRecord;
import com.niq.datamodel.tables.records.ShopperShelfRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in NIQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProductRecord> PRODUCT_PK = Internal.createUniqueKey(Product.PRODUCT, DSL.name("PRODUCT_PK"), new TableField[] { Product.PRODUCT.PRODUCT_ID }, true);
    public static final UniqueKey<ShopperShelfRecord> SHOPPER_SHELF_PK = Internal.createUniqueKey(ShopperShelf.SHOPPER_SHELF, DSL.name("SHOPPER_SHELF_PK"), new TableField[] { ShopperShelf.SHOPPER_SHELF.SHOPPER_ID, ShopperShelf.SHOPPER_SHELF.PRODUCT_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ShopperShelfRecord, ProductRecord> FK_SHOPPER_SHELF_PRODUCT = Internal.createForeignKey(ShopperShelf.SHOPPER_SHELF, DSL.name("FK_SHOPPER_SHELF_PRODUCT"), new TableField[] { ShopperShelf.SHOPPER_SHELF.PRODUCT_ID }, Keys.PRODUCT_PK, new TableField[] { Product.PRODUCT.PRODUCT_ID }, true);
}
