CONNECT NIQ/temp1@//localhost/NIQDB

CREATE TABLE NIQ.PRODUCT
(
  PRODUCT_ID  VARCHAR2(16 BYTE)                 NOT NULL,
  CATEGORY    VARCHAR2(32 BYTE),
  BRAND       VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX NIQ.PRODUCT_PK ON NIQ.PRODUCT
(PRODUCT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE NIQ.PRODUCT ADD (
  CONSTRAINT PRODUCT_PK
  PRIMARY KEY
  (PRODUCT_ID)
  USING INDEX NIQ.PRODUCT_PK
  ENABLE VALIDATE);


CREATE INDEX NIQ.IDX_PRODUCT_BRAND ON NIQ.PRODUCT
(BRAND)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX NIQ.IDX_PRODUCT_CATEGORY ON NIQ.PRODUCT
(CATEGORY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
