CONNECT NIQ/temp1@//localhost/NIQDB

CREATE TABLE NIQ.SHOPPER_SHELF
(
  SHOPPER_ID       VARCHAR2(16 BYTE)            NOT NULL,
  PRODUCT_ID       VARCHAR2(16 BYTE)            NOT NULL,
  RELEVANCY_SCORE  NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX NIQ.SHOPPER_SHELF_PK ON NIQ.SHOPPER_SHELF
(SHOPPER_ID, PRODUCT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE NIQ.SHOPPER_SHELF ADD (
  CONSTRAINT SHOPPER_SHELF_PK
  PRIMARY KEY
  (SHOPPER_ID, PRODUCT_ID)
  USING INDEX NIQ.SHOPPER_SHELF_PK
  ENABLE VALIDATE);


CREATE INDEX NIQ.IDX_SHOPPER_SHELF_PRODUCT ON NIQ.SHOPPER_SHELF
(PRODUCT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE NIQ.SHOPPER_SHELF ADD (
  CONSTRAINT FK_SHOPPER_SHELF_PRODUCT 
  FOREIGN KEY (PRODUCT_ID) 
  REFERENCES NIQ.PRODUCT (PRODUCT_ID)
  ENABLE VALIDATE);

